filename,line_number,pylint_message,pylint_type,pylint_symbol,bandit_issue_text,bandit_issue_confidence,bandit_issue_severity
sevabot-1.0/sevabot/bot/modules.py,76,Line too long (103/100),Category.C,line-too-long,"subprocess call with shell=True identified, security issue.",HIGH,HIGH
sevabot-1.0/sevabot/bot/bot.py,62,"Variable name ""m"" doesn't conform to snake_case naming style",Category.C,invalid-name,"Use of insecure MD2, MD4, MD5, or SHA1 hash function.",HIGH,MEDIUM
